set dotenv-load

serve:
  cargo run

build:
  cargo build --release --bin bestsign-superpeer

add-target: 
  rustup target add x86_64-unknown-linux-gnu

release:
  cargo build --release --bin bestsign-superpeer --target x86_64-unknown-linux-gnu

scp:
  scp -i ~/.ssh/oracle_cloud ../../target/x86_64-unknown-linux-gnu/release/bestsign-superpeer ubuntu@$IP_ADDRESS:~ 

run-on-server:
  ssh -i ~/.ssh/oracle_cloud ubuntu@$IP_ADDRESS './bestsign-superpeer'

login:
  ssh -i ~/.ssh/oracle_cloud ubuntu@$IP_ADDRESS
