name: Rust

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        include:
          # Linux (32-bit)
          - target: i686-unknown-linux-gnu
            platform: ubuntu-latest
            rust: stable
            deps: sudo apt update && sudo apt install gcc-multilib

          # macOS (64-bit)
          - target: x86_64-apple-darwin
            platform: macos-latest
            rust: stable
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Configure Git
        run: |
          git config --global url."git@github.com:".insteadOf "https://github.com/"
      - name: Configure Cargo
        run: |
          mkdir -p ~/.cargo
          echo '[net]' >> ~/.cargo/config.toml
          echo 'git-fetch-with-cli = true' >> ~/.cargo/config.toml
      - run: ${{ matrix.deps }}
      - run: cargo build --target ${{ matrix.target }} --manifest-path crates/core/Cargo.toml --all-features

  wasm_builds:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          rust:
            - 1.83.0 # MSRV
            - stable
          target:
            - wasm32-wasip1
            - wasm32-unknown-unknown
      steps:
        - uses: actions/checkout@v4
        - uses: dtolnay/rust-toolchain@stable
          with:
            toolchain: ${{ matrix.rust }}
            target: ${{ matrix.target }}
        - name: Install SSH Key
          uses: shimataro/ssh-key-action@v2
          with:
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            known_hosts: ${{ secrets.KNOWN_HOSTS }}
        - name: Configure Git
          run: |
            git config --global url."git@github.com:".insteadOf "https://github.com/"
        - name: Configure Cargo
          run: |
            mkdir -p ~/.cargo
            echo '[net]' >> ~/.cargo/config.toml
            echo 'git-fetch-with-cli = true' >> ~/.cargo/config.toml
        - run: cargo build --target ${{ matrix.target }} --manifest-path crates/core/Cargo.toml --features wasm

  test:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          rust:
            - 1.83.0 # MSRV
            - stable
      steps:
        - uses: actions/checkout@v4
        - uses: dtolnay/rust-toolchain@stable
          with:
            toolchain: ${{ matrix.rust }}
        - name: Install SSH Key
          uses: shimataro/ssh-key-action@v2
          with:
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            known_hosts: ${{ secrets.KNOWN_HOSTS }}
        - name: Configure Git
          run: |
            git config --global url."git@github.com:".insteadOf "https://github.com/"
        - name: Configure Cargo
          run: |
            mkdir -p ~/.cargo
            echo '[net]' >> ~/.cargo/config.toml
            echo 'git-fetch-with-cli = true' >> ~/.cargo/config.toml
        - run: cargo test --workspace --verbose --release --manifest-path crates/core/Cargo.toml
        - run: cargo test --workspace --all-features --manifest-path crates/core/Cargo.toml # debug build
        - run: cargo test --workspace --release --all-features --all-targets --manifest-path crates/core/Cargo.toml
